routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

// Route::get('/contact', function () {
//     return view('contact');
// });

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'namespace' => 'Frontend',
    'prefix' => 'contact',
    'as' => 'contact.'
], function() {

    Route::get('/', 'ContactController@index')->name('index');
    Route::get('/confirm', 'ContactController@confirm')->name('confirm');
    Route::get('/success', 'ContactController@success')->name('success');

    Route::post('/pre-confirm', 'ContactController@preConfirm')->name('pre-confirm');
    Route::post('/store', 'ContactController@store')->name('store');
}); 

Route::group([
    'namespace' => 'Backend',
    'prefix' => 'admin',
    'as' => 'admin.contact.',
    'middleware'=> 'auth'
], function() {
    Route::get('/contact', 'ContactController@index')->name('index');
    Route::get('/contact/{any}', 'ContactController@show')->name('show');
    Route::put('/contact/{any}', 'ContactController@put')->name('put');

});

app/Contacts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contacts extends Model
{
    use SoftDeletes;
    public $timestamps = false;
    protected $fillable =['name', 'email', 'phone_number', 'subject', 'message', 'status', 'updated-by'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Contacts;
use Illuminate\Http\Request;


class ContactController extends Controller
{
    public function index(Request $request)
    {
        $key = $request->get('search', null);
        if ($key){
            $contacts= Contacts::where("name", "like","%$key%")
                ->orWhere("email", "like", "%$key%")
                ->orWhere("phone_number", "like", "%$key%")
                ->orWhere("subject", "like", "%$key%")
                ->paginate(10);
        }else{
            $contacts= Contacts::paginate(10);
        }
        return view('backend.contact_list', compact('contacts')); 
    }

    public function show($contactId)
    {
        $contact = Contacts::whereId($contactId)->firstOrFail();
        return view('backend.contact_detail', compact('contact'));
    }

    public function put(Request $request, $contactID)
    {
        $status = $request->status;
        $contact = Contacts::find($contactID);

        if($contact){
            $contact->status =$status;
            $contact->save();
        }

        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Contacts;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(){

        //check and reload data from session
        $contact = null;

        if(session()->has('tmp_contact')){
            $contact = session('tmp_contact');
        }
        return view('frontend.contact', compact('contact'));
    }

    public function preConfirm(Request $request){
        $request->validate([
            'name' =>'required|max:50',
            'email' =>'required|email|max:100',
            'phone_number' =>'required|max:10',
            'subject' =>'required|max:100',
            'message' =>'required'
        ]);
        
        $contact = $request->only(['name', 'email', 'phone_number', 'subject', 'message']);
        //store data to session()
        session(['tmp_contact' => $contact]);

        //redirect to confirm view
        return redirect()->route('contact.confirm');
    }

    public function store(){
       
        //check data in session
        if (session()->has('tmp_contact')) {

            // store data to database
            $contact = session('tmp_contact');
            $contact['updated-by'] = 0;
            $row = Contacts::create($contact);

            if ($row) {
                //clear data from session
                session()->forget('tmp_contact');

                //redirect to success view
                return redirect()->route('contact.success');
            }
        }
        abort(404);
    }


    public function confirm(){

        //check data from session
        $contact = null;
        if(session()->has('tmp_contact')){
            $contact = session('tmp_contact');
        }
        return view('frontend.contact_confirm', compact('contact'));
    }

    public function success(){
        return view('frontend.contact_success');
    }

    



}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/backend/contact_detail.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 pb-4">
                <form action="{{route('admin.contact.put',$contact->id)}}" method="post">
                    @method('PUT')
                    @csrf

                    <button type="submit" class="@if($contact->status =='pending') btn-success @endif btn border border-secondary float-right ml-2"
                            name="status" value="pending">Pending</button>
                    
                    <button type="submit" class="@if($contact->status =='in_progress') btn-success @endif btn border border-secondary float-right ml-2"
                            name="status" value="in_progress">In progress</button>
                    
                    <button type="submit" class="@if($contact->status =='completed') btn-success @endif btn border border-secondary float-right ml-2"
                            name="status" value="completed">Completed</button>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <table class="table table-bordered">
                    <tr>
                        <th scope="row">Name</th>
                        <td>{{$contact->name}}</td>
                    </tr>

                    <tr>
                        <th scope="row">Email</th>
                        <td>{{$contact->email}}</td>
                    </tr>

                    <tr>
                        <th scope="row">Phone Number</th>
                        <td>{{$contact->phone_number}}</td>
                    </tr>

                    <tr>
                        <th scope="row">Subject</th>
                        <td>{{$contact->subject}}</td>
                    </tr>

                    <tr>
                        <th scope="row" style="...">Message</th>
                        <td><p>{{$contact->message}}</p></td>
                    </tr>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/backend/contact_list.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col 12">
            <form action="" method="get">
                <button type=" submit" class="btn btn-primary float-right">Search</button>
                <div class="form-group float-right mr-2">
                    <input type="text" class="form-control" id="search" value="{{$_GET['search'] ?? '' }}" name="search" placeholder="Enter keyword">
                </div>
            </form>
            </div>
        </div>

        <div class="row">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#No</th>
                    <th scope="col">Name</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Email</th>
                    <th scope="col">Status</th>
                    <th scope="col">Date</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @if(!empty($contacts) && $contacts->count() >0)
                    @foreach($contacts as $row)
                        <tr onClick="window.location=''">
                            <th scope="row"># {{$row->id}}</th>
                            <td>{{$row->name}}</td>
                            <td>{{$row->subject}}</td>
                            <td>{{$row->email}}</td>
                            <td>{{$row->status}}</td>
                            <td>{{$row->created_at}}</td>
                            <td>
                                <div class="btn-group float-right">
                                    <a href= "{{route('admin.contact.show', $row->id)}}" class="btn border border-secondary">View</a>
                                    <button type="button" class="btn border border-secondary">Delete</button>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <p>Record not found</p>
                @endif
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-12">
                <p class="float-left mt-4">Total {{$contacts->total()}}</p>
                <div class="list-of-message float-right mt-4">
                    {!! $contacts->withQueryString()->links() !!}
                    <!-- <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#"><</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">></a></li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>   
@endsection
 

resources/views/frontend/contact.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="col-8 offset-2 mb-5">
            <h1 class="border-bottom text-uppercase">Contact Form</h1>
        </div>
        <form class="col-8 offset-2" action="{{route('contact.pre-confirm')}}" method="post">
            @csrf
            <div class ="form-group">
                 <label for="name">Name</label>
                 <input type="text" class="form-control" name="name" id="name" placeholder="Full name" autocomplete="off" 
                        value="{{ old('name') ?? (isset($contact['name']) ? $contact['name']: '') }}">
                 @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                 @enderror
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email" autocomplete="off" 
                        value="{{old('email') ?? (isset($contact['email']) ? $contact['email']: '') }}">
                    @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="phone_number">Phone Number</label>
                    <input type="phone_number" class="form-control" name="phone_number" id="phone_number" placeholder="000 000 000" autocomplete="off" 
                        value="{{old('phone_number') ?? (isset($contact['phone_number']) ? $contact['phone_number']: '') }}">
                    @error('phone_number')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-row">
                <label for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" placeholder="" autocomplete="off" 
                    value="{{old('subject') ?? (isset($contact['subject']) ? $contact['subject']: '') }}">
                @error('subject')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-row">
                <label for="message">Message</label>
                <textarea class="form-control" id="message" name="message" style="min-height: 128px;" autocomplete="off">
                    {{old('message') ?? (isset($contact['message']) ? $contact['message']: '') }}
                </textarea>
                @error('message')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-outline-dark float-right">Next</button>
        </form>
    </div>
    @endsection

resources/views/frontend/contact_confirm.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="col-8 offset-2 mb-5">
            <h1 class="border-bottom text-uppercase">Contact Confirmation</h1>
        </div>
        <div class="col-8 offset-2">
            <table class="table table-bordered">
            <tr>
                <th width="100px">Name</th>
                <td>
                    @isset($contact['name'])
                        {{ $contact['name'] }}
                    @endisset
                </td>
            </tr>
            <tr>
                <th>Email</th>
                <td>
                    @isset($contact['email'])
                        {{ $contact['email'] }}
                    @endisset
                </td>
            </tr>
            <tr>
                <th>Phone Number</th>
                <td>
                @isset($contact['phone_number'])
                    {{ $contact['phone_number'] }}
                @endisset
                </td>
            </tr>
            <tr>
                <th>Subject</th>
                <td>
                @isset($contact['subject'])
                    {{ $contact['subject'] }}
                @endisset
                </td>
            </tr>
            <tr>
                <th>Message</th>
                <td>
                @isset($contact['message'])
                    {{ $contact['message'] }}
                @endisset
                </td>
            </tr>
            </table>
            <div class="mt-2">
                 <a href="{{route('contact.index')}}" type="button" class="btn btn-outline-dark float-left">Back</a>
                 <form method="post" action="{{route('contact.store')}}">
                    @csrf
                    <input type="submit" class="btn btn-outline-dark float-right" name="submit" value="Submit"/>
                 </form>
            </div>
        </div>
    </div>
    @endsection

resources/views/frontend/contact_success.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="col-8 offset-2 mb-5">
            <h1 class="border-bottom text-uppercase">Contact Submited</h1>
        </div>
        <div class="col-8 offset-2">
            <div class="text-center mt-5 pt-5">
                <h2 class="mt-5">Your message have been submit to our system!</h2>
                <h4>Our team will feedback to you soon, Thank you</h4>
            </div>

            <div class="text-center mt-5">
                <button type="button" class="btn btn-outline-dark">GO BACK TO HOME PAGE</button>
            </div>
        </div>
    </div>
    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>